insert into customer(customer_id, email, first_name, last_name, username) values(1, 'katie@fake.com', 'Katie', 'Fake', 'katie');
insert into bank_account(account_id, customer_id, balance) values(1, 1, 900000000);
insert into bank_account(account_id, customer_id, balance) values(2, 1, 20000);
insert into customer(customer_id, email, first_name, last_name, username) values(2, 'liz@fake.com', 'Liz', 'Fake', 'liz');
insert into bank_account(account_id, customer_id, balance) values(3, 2, 500);
insert into bank_account(account_id, customer_id, balance) values(4, 2, 0);
insert into customer(customer_id, email, first_name, last_name, username) values(3, 'joey@fake.com', 'Joey', 'Fake', 'joey');
insert into bank_account(account_id, customer_id, balance) values(5, 3, 98092.23);
insert into bank_account(account_id, customer_id, balance) values(6, 3, 2045234);
insert into bank_account(account_id, customer_id, balance) values(7, 3, 89.23);
insert into bank_account(account_id, customer_id, balance) values(8, 3, 98783.32);
insert into customer(customer_id, email, first_name, last_name, username) values(4, 'chris@fake.com', 'Chris', 'Fake', 'chris');
insert into bank_account(account_id, customer_id, balance) values(9, 4, 2909.23);
insert into bank_account(account_id, customer_id, balance) values(10, 4, 1003.23);